version: '3'
services:
  api:
    build:
      context: ./predict
      dockerfile: Dockerfile.api
    expose:
      - "5001"
      - "8080"
    ports:
      - "5001:5001"
      - "8080:8080"
    links:
      - web-interface:web-interface
  web-interface:
    build: ./web
    volumes:
      - .:/code
    expose:
      - "5000"
      - "80"
    ports:
      - "5000:5000"
      - "80:80"

